export enum UserType {
  USER = 'user',
}

export enum ErrorCode {
  EMPTY_DATA_ERROR = 'EMPTY_DATA_ERROR',
  INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  DATA_ENTRY_ERROR = 'DATA_ENTRY_ERROR',
}
